version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:3.9.1
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - emrebankNetwork

  kafka:
    image: bitnami/kafka:3.5.2
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - emrebankNetwork

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: demobankrootpsw
      MYSQL_DATABASE: bankAccount
    networks:
      - emrebankNetwork
  
  mongodb:
    image: mongo:7-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - emrebankNetwork

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql_data:
  mongo_data:

networks:
  emrebankNetwork:
    driver: bridge
